### ISSUE TITLE
Need clarity on how the SDK will connect to Tableland when there are multiple Validators

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#117]
Creating this issue to capture questions from the discussion in #112 involving how the SDK should connect when we have multiple Validators.

### outstanding questions and thoughts:

 - Where does the `uri` value that is used in a siwe message come from?  A possibility is to use the value of the `host` connection option, but if we go this route how would a host uri map to a Validator.  
 - What does it mean for a Validator to validate the value or `uri` if the Validator doesn't have a specific DNS address?
 - What is the relationship between Validator, Gateway, and DNS address?
 - Will SDK users be required to specify which Validator should be connected to, i.e. a value for the `host` option?  If not, the default value will probably end up receiving the large majority of requests.
 - Does some kind of Validator load balancing behind a single URL (Gateway) make sense?

Note: to match the siwe spec `uri` would need to be a string that conforms to [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986)

A lot of these questions seem related to Validator incentives/payment mechanisms

**Comment by carsonfarmer** [comment]
Closing this as no longer relevant, because the new SDK from #330 how explicitly requires a baseUrl connection to a Validator.

**Comment by joewagner** [comment]
Sounds good!
