### ISSUE TITLE
unsupported getDefaultProvider network for Polygon Mumbai

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland#120]
**Describe the bug**
We have now switched to Polygon Mumbai as our default network... but there is no default provider available in ethersjs for Polygon networks. This means that folks that _don't_ have a provider API key for Infura, Alchemy, or Etherscan run into issues when trying to use Polygon.

**To Reproduce**
To reproduce, simply try to issue a mutating call (such as create or write) using the SDK when connected to Polygon or while simply using the defaults in NodeJS.

**Expected behavior**
There should at least be a sane default, or a handy error indicating how to fix this.

**Additional context**
This is due to our recent move to Polygon by default. We should try to have a default Polygon provider that we use internally to avoid this bug/issue.

**Comment by joewagner** [comment]
I believe this was fixed somewhere in the last 7 months.  I'm closing as part of Linear cleanup.  If this still exists, let's reopen from inside Linear.
