### ISSUE TITLE
calling the `write` method with valid sql that violates a table constraint should throw an error when the caller is waiting for confirmation

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#121]
**Describe the bug**
When you create a table with a primary key, then try to insert duplicate values for that primary key using the `write` method, the method does not throw an error even though the writes do not succeed.

**To Reproduce**
1. Create a table with a primary key.
2. Insert the same value for the primary key twice.

**Expected behavior**
Assuming the caller is using the default value for `skipConfirm` an error should be thrown after the second insert fails.

See chain of messages in Discord for more detail: https://discord.com/channels/592843512312102924/902337528902860820/1012107267816034334

cc: @carsonfarmer

**Comment by joewagner** [comment]
The reason this is happening is because the SDK is expecting the response from a call to `receipt` to have a top level `error` property, example below:
```
{
    "jsonrpc": "2.0",
    "id": 69,
    "result": {
        "ok": true,
        "error": "db query execution failed (code: SQLITE_NOT NULL constraint failed: leaderboard_5_439.id, msg: NOT NULL constraint failed: leaderboard_5_439.id)",
        "error_event_idx": 0
        "receipt": {
            "chain_id": 5,
            "txn_hash": "0xde3594957f955bfc52ce861ab9d0b0c222653e0febb5cb2c5ef2093e33d4cda8",
            "block_number": 7465202
        }
    }
}
```


However in the case that the transaction's SQL failed due to a table constraint violation the response looks like below:
```
{
    "jsonrpc": "2.0",
    "id": 69,
    "result": {
        "ok": true,
        "receipt": {
            "chain_id": 5,
            "txn_hash": "0xde3594957f955bfc52ce861ab9d0b0c222653e0febb5cb2c5ef2093e33d4cda8",
            "block_number": 7465202,
            "error": "db query execution failed (code: SQLITE_NOT NULL constraint failed: leaderboard_5_439.id, msg: NOT NULL constraint failed: leaderboard_5_439.id)",
            "error_event_idx": 0
        }
    }
}
```

We can update the SDK to find and throw both of these cases, or we could update the structure of the response the Validator is sending.
@jsign Do you any thoughts on what we should do here?

**Comment by carsonfarmer** [comment]
According to the [JSON-RPC spec](https://www.jsonrpc.org/specification#response_object), a top level error key is required on error. So we should probably go with that response from the API. With that in mind, we are _already_ not returning spec compliant responses it seems. Because error should actually an object:

> When a rpc call encounters an error, the Response Object MUST contain the error member with a value that is a Object with the following members:
> 
> **code**
> A Number that indicates the error type that occurred.
> This MUST be an integer.
> **message**
> A String providing a short description of the error.
> The message SHOULD be limited to a concise single sentence.
> **data**
> A Primitive or Structured value that contains additional information about the error.
> This may be omitted.
> The value of this member is defined by the Server (e.g. detailed error information, nested errors etc.).

Unless I am misinterpreting the spec here (which is totally possible)? Note that our `result` member is totally up to us, so currently we _are_ spec compliant on that front.

**Comment by carsonfarmer** [comment]
So _probably_ the response _should_ be something like:

```
{
    "jsonrpc": "2.0",
    "id": 69,
    "error": {
       "message":  "db query execution failed (code: SQLITE_NOT NULL constraint failed: leaderboard_5_439.id, msg: NOT NULL constraint failed: leaderboard_5_439.id)",
        "data": {
            "error_event_idx": 0
         },
        "code": <not sure if we have this>
    }
}
```

**Comment by joewagner** [comment]
@jsign @carsonfarmer Maybe both of your points make sense?  Basically the RPC call is successful, and it's response's result just happens to be saying the there was a transaction that had an error.

**Comment by carsonfarmer** [comment]
Ah actually I see now. The response _isn't_ an error, it is totally valid/correct. It just happens to contain information _about_ an error. So actually, it is probably the fact that we need to dig into the result key and pull out the error in that case.

**Comment by carsonfarmer** [comment]
Ha, yes I think we're saying the same thing @joewagner and @jsign?

**Comment by joewagner** [comment]
@carsonfarmer Sorry I was trying to quote reply and I accidentally edited your comment... I really wish github wouldn't let me do that 😮‍💨

**Comment by carsonfarmer** [comment]
Not in the dark per se. The response was getting through it looks like, but it just wasn't being interpreted as an Error. So if you were relying on catching "errors", you'd miss it. But if you were inspecting the response, you'd see the error string etc.

**Comment by carsonfarmer** [comment]
Well I think we're actually talking about two _different_ things. The receipt method call with a response about an error is clearly not an error, and should _not_ be interpreted as one. _But_, there is an option in the SDK to wait for the receipt after a call to a mutating method (i.e., create or write), and _if_ that _valid_ response contains information about an error, then the create or write method _could_ be interpreted as erroring out.

**Comment by joewagner** [comment]
> I see. But just to be sure to make it clear: it shouldn't be interpreted as an error.
Very good point. It's not being interpreted as an error. In the case of callers who want to know if their write has been materialized, they want the `write` method to throw a meaningful error if something went wrong.

**Comment by joewagner** [comment]
> My take would be to not make it error, since that feels hard to distinguish between an uncontrolled error.

In the case the caller of `write` doesn't want to get confirmation this wouldn't error. If they do want confirmation think we need some way to notify them that the SQL statement did not work and why.  
I feel like an error feels more like a JS pattern. It lets devs use a pretty simple try/catch instead of checking properties on returned objects. @carsonfarmer any preference?
