### ISSUE TITLE
As a side effect of updating to siwe v2 the SDK now relies on an implementation of Buffer being available on the global scope

### ISSUE THREAD

**Issue by datadanne** [tablelandnetwork/js-tableland#129]
As a side effect of updating to siwe v2 the SDK now relies on an implementation of Buffer being available on the global scope.

More discussion here: https://github.com/tablelandnetwork/js-tableland/pull/112#discussion_r949049876

**Comment by joewagner** [comment]
@datadanne When I use the latest build of the SDK everything seems to work in the browser and node enviroments.  Do you have any way to reproduce this?
cc: @carsonfarmer

**Comment by datadanne** [comment]
@joewagner I put together a quick demo of how it breaks for me here: https://github.com/datadanne/tableland-js-sdk-buffer-demo

If you follow the commits from oldest to newest it:
1) Adds a very basic webpack setup
2) Adds @tableland/sdk as a dependency and calls `connection.siwe()`

This works with the current published version of the sdk

3) Updates package.json to use a local version of the js sdk, assumes that the js-tableland repo exists in the parent directory of the example and that a dist is built 

The breaks the example

4) Tells webpack to add a polyfill for events
5) Tells webpack to provide a global Buffer

After this the example works again

Does this make sense? I think most web apps that use create-react-app or something have a webpack config that provides a polyfill for events, but not a global Buffer

**Comment by joewagner** [comment]
@datadanne Thank you!

**Comment by carsonfarmer** [comment]
This has also come up as an issue for a user using React to build a web app.
