### ISSUE TITLE
Create SDK variant that provides the D1Database Interface

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland#146]
A particularly good example is https://socket.dev/npm/package/@cloudflare/d1. Additionally, supporting or adopting this type of API means all d1 users are also Tableland users.

**Comment by joewagner** [comment]
I like this a lot! There are lots of SQL db drivers and orms that have established patterns that are familiar to devs, plus like you say we can potentially get some Tableland wrappers for free

**Comment by sanderpick** [comment]
wow, i like this direction a lot. Is the npm lib backend agnostic in some way?

**Comment by carsonfarmer** [comment]
https://github.com/cloudflare/workers-types/blob/master/src/workers.json#L1355
