### ISSUE TITLE
Error TS2339: Property 'then' does not exist on type 'Connection'

### ISSUE THREAD

**Issue by pukykoi** [tablelandnetwork/js-tableland#162]
**Describe the bug**
I followed the instructions from the tutorial [https://docs.tableland.xyz/creating-a-dynamic-nft-with-p5js-and-tableland](https://docs.tableland.xyz/creating-a-dynamic-nft-with-p5js-and-tableland) . 
I get the following errors  
```
ERROR in /data/p5js/src/index.ts
./src/index.ts 36:9-13
[tsl] ERROR in /data/p5js/src/index.ts(36,10)
      TS2339: Property 'then' does not exist on type 'Connection'.

ERROR in /data/p5js/src/index.ts
./src/index.ts 36:14-24
[tsl] ERROR in /data/p5js/src/index.ts(36,15)
      TS7006: Parameter 'connection' implicitly has an 'any' type.
```
I don't know if this is related, but earlier in the output, I also have the following errors:  
```
ERROR in ./node_modules/safe-buffer/index.js 3:13-30
Module not found: Error: Can't resolve 'buffer' in '/data/p5js/node_modules/safe-buffer'
[...]
ERROR in ./node_modules/@tableland/sdk/dist/esm/src/lib/util.js 12:0-35
Module not found: Error: Can't resolve 'buffer' in '/data/p5js/node_modules/@tableland/sdk/dist/esm/src/lib'
```

**To Reproduce**
1. Go to project directory
2. run `npm run start`
3. See error

**Expected behavior**
The app should be started at url http://localhost:8080

**Other details**
I run node in a docker container. I had the same errors both with the images _node:alpine_ and _node:lts_

Thank you

**Comment by joewagner** [comment]
@pukykoi Looks like our docs are out of date.  `connect` is synchronous in sdk version 3, hence it no longer returns a promise.
@dtbuchholz How should we go about updating the docs?

If you want to get the example working, you should be able to do something like:
```
const connection = connect({ network: "testnet" });
// Run a SQL select on our project table
connection.read("select * from canvas_5_4")
.then(data => {
    // Format and store our data in the points[] array
    points = data.rows
    .map((d, id) => ({x: d[2], y: d[3], id}))
})
```

**Comment by dtbuchholz** [comment]
@joewagner updated! Thanks for the snippet.

**Comment by pukykoi** [comment]
I confirm that the snippet worked on my side.
Thank you
