### ISSUE TITLE
[JST-13] Add a controller contract factory for more advanced ACL features

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/js-tableland#175]
**Is your feature request related to a problem? Please describe.**
Enable the ability to deploy a controller contract from the SDK, or, specific a "preset" contract (ones in which the Tableland team has deployed). Without this, smart contract development is required to access advanced ACL capabilities.

**Describe the solution you'd like**
- Create a new file `create-controller.ts` (or consolidate with other controller files) with a `createController` method that will call `deployController` from `eth-calls.ts`.
- It should allow a developer to specify an optional `contractName`, `policy` (equivalent to `ITablelandController`'s `Policy`), `policyPreset` (some type / enum for deployed controller contracts, like "allow all," "allow all inserts," etc.), and the other related on-chain options like `skipConfirm`. The `contractName` and `policy` should be passed to `deployController` to allow for a `TablelandController` contract to be deployed. If `policyPreset` is specified, that means an existing controller contract will be used, so there's no need to deploy one. The preset controller contracts must be deployed as "global" contracts, per chain, as an independent step.
- Add a `deployController` method in `eth-calls.ts`, which should leverage contracts from `@tableland/evm` (similar to how `createTable` works). Here, the `ITablelandController` (or `ITablelandController__factory`) can be leveraged.
- Note: I tried prototyping this a bit but ran into issues for how to instantiate an interface with _just_ ethers. E.g., how can you implement `getPolicy` in just TS? Curious if I was overcomplicating things, but I'm assuming there's a TS->Solidity->compile set of steps required. Also, since this feature requires contract deployment, it might make sense to consider how `evm-tableland` deploys contracts with hre's ethers (hardhat isn't a dependency in this repo, though).

**Describe alternatives you've considered**
We need this in the SDK. The alternative is to write your own contract, which isn't feasible for JS/TS devs -- e.g., they'd have to [deploy controllers on Remix](https://docs.tableland.xyz/using-remix#8d7a15770af84fef946e6fbf7b6b2e6b) or similar.

**Additional context**
See original [tension](https://www.notion.so/textile/SDK-users-need-a-way-to-create-TablelandController-contracts-and-or-use-a-registry-of-deployed-contr-c524e382badf4e85b3f34ffd94f765bb) and [proposal](https://www.notion.so/textile/We-should-add-an-ACL-contract-factory-to-the-SDK-deploy-standard-controller-contracts-f51f0ed0cd284c8691f27f3a055d9d80).

<sub>[JST-13](https://linear.app/tableland/issue/JST-13/add-a-controller-contract-factory-for-more-advanced-acl-features)</sub>

**Comment by sanderpick** [comment]
Digging how you're thinking about this. I've been thinking about another path we could take involving extending the power of `GRANT` to do more complex things. We have some working sessions to address the overall topic of consolidating access control next week... I'll wait till we do that before dumping thoughts here.

**Comment by dtbuchholz** [comment]
cool, makes sense. i think that definitely would make it easier to implement access control in the SDK (e.g., `where` clause with a `grant`), which i believe you had mentioned as an idea there.

**Comment by joewagner** [comment]
I'm adding this to Linear.  I think this kind of thing will be part of the Table Config project.

**Comment by sanderpick** [comment]
@joewagner i just peaked into this project… I think a good first step would be a notion design doc. i'll add an issue for that.

**Comment by sanderpick** [comment]
guessing we can cancel this aspect of the "tableland projects" right? or is this part of your and Aaron's plan?
