### ISSUE TITLE
Make error message meaningful if this lib cannot get a signer 

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#262]
**Describe the bug**
If no signer is provided to the connect method, this lib will assume the environment is a browser and try to get the signer from the global `ethereum` object.  If `globalThis.ethereum` doesn't exist the error will be "Cannot read properties of undefined (reading 'request')".
This error is not very useful.  We should add a check [here](https://github.com/tablelandnetwork/js-tableland/blob/main/src/lib/util.ts#L18) that does something like:

```
if (!globalThis.ethereum) {
  throw new Error("Tableland: no signer provided and cannot get a signer from global scope");
}
```
 

**To Reproduce**

1. connect to tableland without providing a signer in an enviroment without globalThis.ethereum

**Expected behavior**
A useful error should be thrown

**Comment by joewagner** [comment]
cc: @carsonfarmer I didn't make a PR for this yet in case you already started the a wip refactor we talked about on Friday.

**Comment by carsonfarmer** [comment]
Yeh let's hold off for now. In the new refactor, you essentially won't be able to _not_ provide a signer, so this might be "go away".

**Comment by joewagner** [comment]
Sounds good.  If I remember right the requirement of providing a signer was removed so that reads would work without a wallet, but we can discuss in the refactor review.
