### ISSUE TITLE
Why are CreateTableReceipt fields optional?

### ISSUE THREAD

**Issue by asutula** [tablelandnetwork/js-tableland#271]
**Is your feature request related to a problem? Please describe.**
Yes, the `CreateTableReceipt` fields `name`, `prefix`, and `tableId` are optional (`?`), but I can't think of why they should be. Presumably, the SDK will detect any receipt `error` and throw it, otherwise return the resulting data to the SDK user, which should always include those properties.

**Describe the solution you'd like**
They should not be optional.

**Describe alternatives you've considered**
Dealing with the optionals which is a pain when it's not necessary.

**Additional context**
None

**Comment by joewagner** [comment]
This might be at least partially left over from earlier sdk versions.
name and prefix are always `string`.  `prefix` might be the empty string, but that should be ok.  Changing those to not be optional makes sense to me.

For the tableId, it looks like [`event.args` is optional](https://github.com/tablelandnetwork/js-tableland/blob/main/src/lib/create.ts#L42), but maybe the sdk should throw if tableId available? That would be a runtime error, and I'm not sure when that would happen.  Or what the right sdk behavior would be if the transaction succeeds but the tableId isn't available?

cc: @carsonfarmer maybe try to capture this in the refactor you're working on?

**Comment by carsonfarmer** [comment]
Cool, yeh in the refactor these are not optional, because I ran into likely the same issues that @asutula is describing here. Let's leave this one open though to make sure it is properly captured!

**Comment by asutula** [comment]
Thanks guys!
