### ISSUE TITLE
Update testnet chains connection objects to point to new testnets gateway

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#309]
The upcoming ship of the new gateway will include a change in the url from https://testnet.tableland.network to https://testnets.tableland.network
We need to make that change in util.ts and ensure that publishing the change happens in coordination with the ship

**Comment by carsonfarmer** [comment]
Actually, shouldn't this change be in @tableland/evm? Which is actually where downstream consumers (such as js-textile) should be pulling from?

**Comment by joewagner** [comment]
@carsonfarmer I like the idea of moving the gateway json to evm-tableland.
I think there's potentially 2 related pieces of work to do:
1.  Currently this lib gets the gateway urls from the util.ts file, e.g. https://github.com/tablelandnetwork/js-tableland/blob/main/src/lib/util.ts#L69 We can/should switch that data to living in evm-tableland similar to `evm.proxies`.
2. We need to change the value of the url to match the new gateway

For number 1, we can make that change whenever it's ready.  Do you know if we captured that work somewhere in evm-tableland issues?
For number 2, we need to make sure npm versions all line up to use the new gateway in sync with the upcoming ship. This will require some stuff to be done here, which is what I was thinking this ticket would track.

There are some longer term issues related to this, that I'll link below just for some context. Nothing proessing, but some background on how this might work in the future:
https://github.com/orgs/tablelandnetwork/discussions/242
