### ISSUE TITLE
Source map points to missing source files

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#33]
The build of this code base that is published to npm contains `.map` files with reference to the src directory.  The src directory is not published to npm which means that frontend tooling like [Vite](https://vitejs.dev/) send out many Warnings anytime this package is used.

look in `dist/esm/src/main.js.map`, you will see the following JSON

```
{"version":3,"file":"main.js","sourceRoot":"","sources":["../../../src/main.ts"],"names":[],"mappings":"AAAA,OAAO,EAAE,OAAO,EAAE,MAAM,oBAAoB,CAAC;AAC7C,cAAc,iBAAiB,CAAC"}
```

Note that the "sources" property refers to `../../../src/main.ts`.  That file is not published to npm, hence the warnings from Vite

**Comment by joewagner** [comment]
Looks like the "files" prop in package.json is used to exclude the `src/` directory

**Comment by carsonfarmer** [comment]
Yup exactly, we can just add the src dir to files to fix this.
