### ISSUE TITLE
The description option no longer works

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#34]
## Expected Behavior
When using the SDK to create a table, the caller used to be able to add a description to the table via an options Object

## Actual Behavior
The description is ignored

## Steps to Reproduce the Problem

1. Call the `create` function with an options object containing a description property
2. Call the `list` function with the same wallet as step one and notice that no description exists

**Comment by buchhlz2** [comment]
@joewagner just took a quick glance into the code -- not sure if this is the issue. But in `tableland-calls.ts`, the `create` method doesn't pass in everything that's part of the `options`. Is the fix to add the `description` (and whatever else is missing), e.g., https://github.com/buchhlz2/js-tableland/blob/5c070b7d87c01c257573d0283eef1565965a9c69/src/lib/tableland-calls.ts#L62

**Comment by buchhlz2** [comment]
@joewagner Just took a quick glance at `tableland-calls.ts` -- not sure if this is the issue. But it looks like the `description` is not passed? E.g., should it be added here?:
```
...
const message = await GeneralizedRPC.call(this, "createTable", {
    tableId: tableId,
    statement: query,
    dryrun: options.dryrun,
    description: options.description
```
https://github.com/tablelandnetwork/js-tableland/blob/5c070b7d87c01c257573d0283eef1565965a9c69/src/lib/tableland-calls.ts#L94

**Comment by joewagner** [comment]
> @joewagner Just took a quick glance at `tableland-calls.ts` -- not sure if this is the issue since I'm not too familiar with the codebase. But, in the `create()` function, it looks like the `description` is not passed to `GeneralizedRPC.call()` as an option? E.g., should it be added here?:
> 
> ```
> const message = await GeneralizedRPC.call(this, "createTable", {
>     tableId: tableId,
>     statement: query,
>     dryrun: options.dryrun,
>     description: options.description // add the `description`
>   });
> ```
> 
> https://github.com/tablelandnetwork/js-tableland/blob/5c070b7d87c01c257573d0283eef1565965a9c69/src/lib/tableland-calls.ts#L94

Nice!  Thanks for the help here, pushing a fix now
