### ISSUE TITLE
SDK failing to parse souce map from `@tableland/evm`; no such file

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/js-tableland#355]
**Describe the bug**
I've installed the Tableland SDK v4.0.0-pre.2, imported it into my React app, and tried to simply import the `Database` object. There are compile errors complaining about `@tableland/evm` files not existing and source map issues.

**To Reproduce**
1. Create a React app: `npx create-react-app test`
2. Then: `cd test && npm i`
3. Install the SDK:`npm i @tableland/sdk@4.0.0-pre.2`
4. Simply import the SDK into `App.js`: `import { Database } from "@tableland/sdk";`
5. Run the app: `npm run start`

Errors are then thrown, and the SDK does not work (e.g., if trying to add functionality instead of simply an import)—here are the errors:
<details>
<summary>Failed to parse source map from '/Users/dtb/Desktop/test/node_modules/@tableland/evm/...' file: Error: ENOENT: no such file or directory</summary>

```
Failed to parse source map from '/Users/dtb/Desktop/test/node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable__factory.ts' file: Error: ENOENT: no such file or directory, open '/Users/dtb/Desktop/test/node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable__factory.ts'

Failed to parse source map from '/Users/dtb/Desktop/test/node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/dtb/Desktop/test/node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/index.ts'

// A ton of more error messages that caused this comment to exceed the maximum size limit

WARNING in ./node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable__factory.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/dtb/Desktop/test/node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable__factory.ts' file: Error: ENOENT: no such file or directory, open '/Users/dtb/Desktop/test/node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable__factory.ts'

WARNING in ./node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/dtb/Desktop/test/node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/dtb/Desktop/test/node_modules/@tableland/evm/typechain-types/factories/@openzeppelin/contracts-upgradeable/access/index.ts'

```
</details>

**Expected behavior**
No errors upon importing the SDK.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Mac
- Google Chrome
- Node v18.12.1
- `@tableland/sdk@v4.0.0-pre.2`

**Comment by joewagner** [comment]
@dtbuchholz Thanks for finding this.  I'm able to reproduce and I'll dig into finding a fix now.

**Comment by joewagner** [comment]
The fix to evm-tableland has made it to main, once that change is published we will need to update that dependency here and this will be fixed.

**Comment by dtbuchholz** [comment]
Cool, I'll keep an eye out (or just lmk)—I'll test things out on my end, too.

**Comment by joewagner** [comment]
@dtbuchholz In the example I setup to reproduce this, it is now working as of version `4.0.0-pre.3` of the SDK.  Are you ok closing this?
