### ISSUE TITLE
Incorrect types for query responses

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland#36]
It looks like the Typescript types for query responses are currently incorrect. Whereas I would expect, based on the types that the following returns an object with `columns` and `rows`, I actually get an object with `{ data: { columns, rows } }`. However, the Typescript compiler complains with `Property 'data' does not exist on type 'ReadQueryResult'.`. The fix is to either automatically destructure the returned object (internally) and return rows and columns, or to update the types to reflect the fact that the data is structured under the data key. The former seems like the nicer option.

```
const response = await connection.query(`select * from some_table;`);
```

**Comment by joewagner** [comment]
@carsonfarmer Are you thinking have the SDK return an Array of Objects instead of the values of the column names and rows?
For example:

```
// current
{
  "columns": [{"name": "tweet"}, {"name": "tweet_id"}],
  "rows": [
    ["Account 4 here.  All looks well", 1], ["Tuesday evening, coding is fun", 2]
  ]
}

// new
[
  {
    tweet: "Account 4 here.  All looks well",
    tweet_id: 1
  }, {
    tweet: "Tuesday evening, coding is fun",
    tweet_id: 2
  }
]
```

**Comment by carsonfarmer** [comment]
Are you sure that the above "current" is correct? I don't think it is in practice. You get this:

```
{ 
  data: {
    "columns": [{"name": "tweet"}, {"name": "tweet_id"}],
    "rows": [
      ["Account 4 here.  All looks well", 1], ["Tuesday evening, coding is fun", 2]
    ]
  }
}
```

Try it with a real call to the gateway, versus the mocked responses.

**Comment by carsonfarmer** [comment]
➜ tableland query "select * from svelte_todo_demo_689 order by status;"
{
  "data": {
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "status"
      },
      {
        "name": "name"
      },
      {
        "name": "description"
      },
      {
        "name": "project"
      },
      {
        "name": "context"
      }
    ],
    "rows": [
      [
        0,
        "Pending",
        "First task",
        "This is the first of many tasks",
        "Project One",
        "Focus Time"
      ]
    ]
  }
}

**Comment by joewagner** [comment]
Your's is more complete.  I was just showing the data property
