### ISSUE TITLE
[JST-12] 3rd Party: Test/add support for Drizzle ORM

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland#381]
https://github.com/drizzle-team/drizzle-orm

<sub>[JST-12](https://linear.app/tableland/issue/JST-12/3rd-party-testadd-support-for-drizzle-orm)</sub>

**Comment by sanderpick** [comment]
I think one is done, correct?

**Comment by joewagner** [comment]
> I think one is done, correct?

Think so!  There's still a little bit of work needed to get drizzle working in some cases, but once #542 is finished it will be pretty trivial to use Drizzle

**Comment by joewagner** [comment]
> Sounds good. It's currently part of the Tableland Projects project... does that still make sense?

Yeah, that makes sense
