### ISSUE TITLE
[JST-16] Scope out different approaches to namespacing

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland#456]
cc @carson @awmuncy sounds like this is the next step. I put this in cycle 3.

<sub>From [SyncLinear.com](https://synclinear.com) | [JST-16](https://linear.app/tableland/issue/JST-16/scope-out-different-approaches-to-namespacing)</sub>

**Comment by sanderpick** [comment]
👍

**Comment by awmuncy** [comment]
@carsonfarmer @joewagner and I talked about this a bit yesterday. The two main points were: 

1. No reason to be ENS focused; anything that can plug in a list K/V pairs will do. 
2. We might simply say "Use an ORM". Apparently Aaron has been using a very slick ORM that "just works" with tableland, and can handle aliasing tables pretty well (I'm hearing it second hand, correct me if I'm wrong @asutula)

   I think we could safely incubate the namespacing beyond ENS idea for a while, then maybe in a few cycles come back to it for consideration, after the ENS in CLI has been release in the docs for a bit.

**Comment by sanderpick** [comment]
quick question: the ENS in the CLI is still behind the experimental flag right? and in the docs? Just making sure that it's going to be painless to deprecate if we need to later.

**Comment by awmuncy** [comment]
Yes, it's behind a very explicit flag: `--enableEnsExperiment`. The ENS stuff will be at the bottom of their respective CLI command's page in the docs, and will have a big callout before the command clarifying that is extra experimental, no promises about future usability.

**Comment by asutula** [comment]
The ORM stuff I'm using still requires some custom glue to make it work with Tableland. The ORM schema definitions let you provide a vanilla table name ("users" for example), and I was able to write some custom code (via an ORM callback) that assures that when a query is constructed using the ORM, the correct actual table name is resolved as a function of what chain you are on. I'm not sure I would call that "namespaces", but it's a nice way to not have to worry about table ids.

**Comment by sanderpick** [comment]
@awmuncy let's cancel / complete this issue for now. i'll make sure the topic is covered in litepaper scoping.
