### ISSUE TITLE
[JST-26] Enable support for INSERT + GROUP BY subqueries

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/js-tableland#493]
With updates to the parser ([GSP-14](https://linear.app/tableland/issue/GSP-14/add-group-by-support-for-insert-subqueries) / [wasm PR](https://github.com/tablelandnetwork/wasm-sqlparser/pull/208)), the SDK should make sure that it supports INSERT + GROUP BY subqueries. At a minimum, this means bumping the `@tableland/sqlparser` dep version, but in case there are any tests etc. that touch on previously disable feature, these have to be updated as well.

<sub>From [SyncLinear.com](https://synclinear.com) | [JST-26](https://linear.app/tableland/issue/JST-26/enable-support-for-insert-group-by-subqueries)</sub>

**Comment by joewagner** [comment]
fixed by #510
