### ISSUE TITLE
Need smoke-screen tests to ensure that the SDK works with an actual Tableland Network

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#54]
We should have at least a few tests that make actual http requests and smart contract calls to a publicly available Tableland Network.  I'll suggest that this can be the "staging" Tableland Network, but testnet could work too, or we could add the tooling to spin up a network via https://github.com/textileio/local-tableland

**Comment by sanderpick** [comment]
Local might be nicer, otherwise we’d have to manage a wallet for tests, but that might not be too much of a headache

**Comment by joewagner** [comment]
All that said, long term being able to use a local network seems good and doable once go-tableland is public
