### ISSUE TITLE
Exported members are not visible

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland#60]
Seems that TS doesn't like some of these imports:

```
import { nextError } from "@tableland/sdk";
```

and

<img width="817" alt="Screen Shot 2022-06-17 at 5 43 53 PM" src="https://user-images.githubusercontent.com/361000/174415759-fc459ef5-f735-45b9-a86f-672b6ef1ac1a.png">

**Comment by joewagner** [comment]
The `import { nextError } from "@tableland/sdk";` error is part of the test mocking. That should get changed with https://github.com/tablelandnetwork/js-tableland/issues/60.
The `ConnectOptions` error makes it look like you might have an older version of the SDK?

**Comment by sanderpick** [comment]
> The import { nextError } from "@tableland/sdk"; error is part of the test mocking. That should get changed with https://github.com/tablelandnetwork/js-tableland/issues/54.

👍 

I'm looking here in site-tableland on main: https://github.com/tablelandnetwork/site-tableland/blob/main/store/index.ts#L2

**Comment by joewagner** [comment]
> > The import { nextError } from "@tableland/sdk"; error is part of the test mocking. That should get changed with #54.
> 
> 👍
> 
> I'm looking here in site-tableland on main: https://github.com/tablelandnetwork/site-tableland/blob/main/store/index.ts#L2

Weird, can you look in `node_modules/@tableland/sdk/package.json` and see what's installed?

**Comment by sanderpick** [comment]
oh, duhhh... didn't install, classic. i'll close this 🙏
