### ISSUE TITLE
Replace "hash" function with "validateCreate" function and match "create" API

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland#62]
Since you don't actually write your own create statements if you are using the SDK (or the CLI), we should just match that API in the validation function as well. Additionally, hash is slightly misleading, because the name doesn't reflect what the API is really designed for... validation.

**Comment by carsonfarmer** [comment]
I'm fine with keeping the name I guess? The confusion came from a discussion on Discord. Seems like a dryrun create option is a good idea 👍, so let's go with that. 

In other words, have hash match the create api, and add an options arg to create with a dryrun option. It might be nice to collapse prefix into that options arg as well?

**Comment by joewagner** [comment]
Nice, I like putting pefix into the options.
I'm curious what was the discord discussion?
