### ISSUE TITLE
Create CI flow to publish to NPM

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland#68]
Like https://github.com/textileio/go-threads/blob/master/.github/workflows/publish-grpc-libs.yml

**Comment by joewagner** [comment]
We have https://github.com/tablelandnetwork/js-tableland/blob/main/.github/workflows/publish.yml as of https://github.com/tablelandnetwork/js-tableland/commit/faeb252aa2a88757b22cc27ae75d73f9bfdd5049.  Does that handle everything in this issue?
