### ISSUE TITLE
Notion integration has trouble parsing markdown

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#86]
## Expected Behavior
I can open an issue in github using the issue template

## Actual Behavior
This is a test to see if I can open an issue using the template

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

#83 contains 2 unrelated problems.  I'm splitting this into it's own issue.

**Comment by joewagner** [comment]
@eightysteele Looks like our default issue template doesn't work with the workflow to add issues to Notion.  Any idea how this could be fixed?

@wbt discovered this recently, thanks!
@wbt mentioned that it might be that the markdown headers are part of the problem, e.g. `## Expected Behavior`
Here's the failed workflow: https://github.com/tablelandnetwork/js-tableland/actions/runs/2745918606

**Comment by eightysteele** [comment]
seems like fabric shutdown, so looking at alternatives now (including native notion support for db sync).

**Comment by joewagner** [comment]
This should be fixed by #91
