### ISSUE TITLE
list() and create() calls fail in Node.js with ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by narteysarso** [tablelandnetwork/js-tableland#92]
## Expected Behavior
Tableland calls ( list and create) should successfully execute in nodejs

## Actual Behavior
Tableland calls (list and create) fail with the error `ReferenceError: fetch is not defined`

## Steps to Reproduce the Problem

1.  setup nodejs app
2.  npm i @tableland/sdk
3.  implement [https://docs.tableland.xyz/javascript-sdk](https://docs.tableland.xyz/javascript-sdk) for Node.js(require)

## Specifications

- Version: 3.0.0
- Platform: nodejs on windows

**Comment by narteysarso** [comment]
## My workaround 
Fetch is not natively supported in Node.js as such it fails with reference error. 
I added [node-fetch module globally ](https://github.com/node-fetch/node-fetch#providing-global-access) to index.js
```
const fetch = require("node-fetch");

if (!globalThis.fetch) {
    globalThis.fetch = fetch;
}

```

**Comment by joewagner** [comment]
@narteysarso thanks for posting.  node.js >= 16.5  does support fetch natively, but you may need to use the `--experimental-fetch` flag.
If you want to use an older version of node.js your workaround should work well
