### ISSUE TITLE
Use polygon-mumbai as default chain

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland#94]
Right now the default is Goerli, which is our slowest chain. Mumbai has been really popular at hackathons and it's fast.

**Comment by dtbuchholz** [comment]
Nre note that we'll want to create outcomes to update the docs/devx things...a few that come to mind:
1. Remove explicit mentions of "ethereum-goerli" as the default network and swap for "polygon-mumbai".
2. Update/re-create every docs example/snippet in the SDK and CLI pages to use mumbai over goerli (e.g., table names, ids, tx hashes).
3. Announce changes in Discord -- devs who weren't explicitly passing `chain` were defaulting to eth goerli, so upon updating to the latest version of the SDK, they'll need to make the necessary changes.
4. (Optional) consider updating existing example apps if using eth goerli

**Comment by joewagner** [comment]
+1 for updating example apps.
An additional note, Polygon Mumbai works with testnet opensea to enable viewing example apps that include NFTs
